resolver: lts-13.26

packages:
- .

extra-deps:
- git: https://github.com/purescript/purescript
  commit: 9cad73ed8ea7df3011032ddbd2f3de5a0c08629c
- happy-1.19.9
- language-javascript-0.7.0.0
- network-3.0.1.1
- these-1.0.1
- semialign-1

nix:
  enable: false
  shell-file: stack.nix

flags:
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
    quickcheck: false
